#ifndef TOMAHAWK_TOMAHAWKCALCPARAMETERS_CPP_
#define TOMAHAWK_TOMAHAWKCALCPARAMETERS_CPP_

#include "TomahawkCalcParameters.h"

namespace Tomahawk{



}

#endif /* TOMAHAWK_TOMAHAWKCALCPARAMETERS_CPP_ */
